#!/bin/bash

# Download a Wikidata JSON dump unless it has already been downloaded

if [[ "$1" =~ ^20[1-9][0-9][01][0-9][0-9][0-9]$ ]]
then
    DATE=$1
    FILE=wikidata-${DATE}-all.json.gz
    URL=https://dumps.wikimedia.org/wikidatawiki/entities/${DATE}/${FILE}

    if curl --output /dev/null --silent --head --fail "$URL"
    then
        echo ${DATE}/${FILE}
        mkdir -p $DATE
        cd $DATE
        wget -N $URL
        STATUS=$?
        cd -
        exit $?
    else
        echo "URL not found: $URL" >&2
    fi
else
    echo "Usage: $0 YYYYMMDD" >&2
fi

exit 404
